import Banner from "@/components/home/home.banner";
import BestSelling from "@/components/home/home.section.best.selling"
import ListCategory from "@/components/home/home.section.list.category";
import { getProduct } from "@/services/service.product";
import ProductCard from "@/components/app.product.cart";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Page() {
  const res = await getProduct()
  let bestSellProducts = []
  if (res?.status === 200) {
    bestSellProducts = res.metadata
  }
  return (
    <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start w-full">
      <Banner />
      <section className="container mx-auto">
        <h2 className="font-[400] text-[1.5rem]">Best-Selling Products</h2>
        <div style={{ display: 'none' }} className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
          {
            bestSellProducts.length > 0 && (
              bestSellProducts.map((product) => (
                <ProductCard key={product._id} product={product} />
              ))
            )
          }
        </div>
      </section>
      <BestSelling products={bestSellProducts} />
      <ListCategory />
    </main >
  );
}