import Banner from "@/components/home/home.banner";
import BestSelling from "@/components/home/home.section.best.selling"
import ListCategory from "@/components/home/home.section.list.category";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start w-full">
      <Banner />
      <BestSelling />
      <ListCategory />
    </main>
  );
}
